config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings
  root 'listings#index'
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates_presence_of :image

  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user)
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find_by(id: params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4>#{sentence}</h4>
        #{messages}
      </div>
      HTML
      html.html_safe
    end
  end

app/helpers/listings_helper.rb
module ListingsHelper
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2016</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EtsyDemo </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Manage Listings", seller_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>




        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsydemo</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navbar' %>
    <div class="container">

    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    
    </div>
    <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-warning alert-dismissable" role="alert">

      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

  
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control", placeholder:"Enter the listing name" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control", placeholder:"Enter the description, keep short and concise  " %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class:"form-control", placeholder:"Enter selling price" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class:"btn btn-link" %> |
<%= link_to 'Back', listings_path, class:"btn btn-link" %>

app/views/listings/index.html.erb
<div class="center">
  <h1>Listings</h1>

    <div class="row">
      <% @listings.each do |listing| %>
          <div class="col-md-3">
            <%= link_to image_tag(listing.image.thumb), listing  %>
            <div class="caption">
              <h3><%= link_to listing.name, listing %></h3>
              <p><%= number_to_currency listing.price %></p>
              <p><%= listing.user.name %></p>
              <% if (user_signed_in?) && (current_user == listing.user) %>
              <%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-link" %>
              <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
              <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <br>
  <% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class:"btn btn-link" %>
  <% end %>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<div class="center">
  <h1>Listings</h1>

    <div class="row">
      <% @listings.each do |listing| %>
          <div class="col-md-3">
            <%= link_to image_tag(listing.image.thumb), listing  %>
            <div class="caption">
              <h3><%= link_to listing.name, listing %></h3>
              <p><%= number_to_currency listing.price %></p>
              <p><%= listing.user.name %></p>
              <% if (user_signed_in?) && (current_user == listing.user) %>
              <%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-link" %>
              <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-link" %>
              <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <br>
  <% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class:"btn btn-link" %>
  <% end %>
</div>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <%= image_tag @listing.image.medium %>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <h5><%= number_to_currency @listing.price %></h5>
    <p><%= @listing.description %></p>
  </div>
</div>


<% if (user_signed_in?) && (current_user == @listing.user) %>
<%= link_to 'Edit', edit_listing_path(@listing), class:"btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class:"btn btn-link" %>

app/views/pages/about.html.erb
<h1>Welcome to Etsydemo!</h1>
<h2>Etsydemo is an online marketplace for buying and selling handmade goods.</h2>

app/views/pages/contact.html.erb
<h1>Email us at abc@etsydemo.com</h1>